<?php

namespace AppBundle\Repository;

/**
 * BordereauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BordereauRepository extends \Doctrine\ORM\EntityRepository
{
}
