<?php

namespace AppBundle\Repository;

/**
 * Cas_a_traiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cas_a_traiteRepository extends \Doctrine\ORM\EntityRepository
{
}
