<?php

namespace AppBundle\Repository;

/**
 * CasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasRepository extends \Doctrine\ORM\EntityRepository
{
}
