<?php

namespace AppBundle\Repository;

/**
 * ConstanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstanteRepository extends \Doctrine\ORM\EntityRepository
{
}
