<?php

namespace AppBundle\Repository;

/**
 * Motif_consultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Motif_consultationRepository extends \Doctrine\ORM\EntityRepository
{
}
