<?php

namespace AppBundle\Repository;

/**
 * PECRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PECRepository extends \Doctrine\ORM\EntityRepository
{
}
