<?php

namespace AppBundle\Repository;

/**
 * rendez_vousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rendez_vousRepository extends \Doctrine\ORM\EntityRepository
{
}
