<?php

namespace AppBundle\Repository;

/**
 * VisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisteRepository extends \Doctrine\ORM\EntityRepository
{
}
